name: Generate Albums and Deploy GH-Pages

on:
  workflow_dispatch:
    inputs:
      years:
        description: 'Comma-separated list of years to generate (e.g. 2020,2021)'
        required: true
        default: '2025'

  push:
    branches:
      - master
    paths:
      - "albums/*.txt"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo with full history (needed for git diff)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies
      - run: npm ci

      # Determine years to build
      - name: Set YEARS variable
        id: set-years
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "years=${{ github.event.inputs.years }}" >> $GITHUB_OUTPUT
          else
            YEARS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
              | grep '^albums/' \
              | sed -E 's|albums/([0-9]+)\.txt|\1|' \
              | sort -u \
              | paste -sd "," -)
            echo "years=$YEARS" >> $GITHUB_OUTPUT
          fi

      # Generate the service-account file from the repo secret
      - name: Setup Google Service Account
        run: |
          printf "%b" "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > topalbums-service-account.json


      - name: Check generated service account
        run: cat topalbums-service-account.json

      # Run your script for each year
      - name: Generate JSON and index
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: |
          echo "Generating albums for years: ${{ steps.set-years.outputs.years }}"
          for YEAR in $(echo "${{ steps.set-years.outputs.years }}" | tr "," " "); do
            node fetch-covers.js "$YEAR"
          done

      # Commit changes
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update and publish for years ${{ steps.set-years.outputs.years }}" || echo "No changes to commit"

      # Push changes back to master
      - name: Push changes
        run: |
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}